---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cahce
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  vars:
    create_users_deploy_user: root
  roles:
    - "role_create_users"
